# Generated by Django 5.0.7 on 2024-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='availability',
            field=models.CharField(default='Anytime', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='timeline',
            field=models.CharField(default='As soon as possible', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='estimated_closing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
