# Generated by Django 5.0.7 on 2024-07-15 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inquiry_availability_inquiry_offer_inquiry_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.salesperson'),
        ),
    ]
