# Generated by Django 5.0.7 on 2024-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
