# Generated by Django 5.0.7 on 2024-07-17 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_inquiry_property_purchaser_inquiry_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='property_purchaser',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.property'),
        ),
    ]
