# Generated by Django 5.0.7 on 2024-07-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_review_property_purchaser_review_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='additional_photos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='core.property')),
            ],
        ),
    ]
