# Generated by Django 5.0.7 on 2024-07-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_additionalphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_footage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
