# Generated by Django 5.0.7 on 2024-07-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_property_land_size_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bathrooms',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
