# Generated by Django 5.0.7 on 2024-07-28 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_property_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
