name: 'Deployment'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    name: 'deployment'
    runs-on: ubuntu
    environment: production

    steps:

    - name: checkout 
      uses: actions/checkout@v2

    - name: install SSH key 
      uses: shimataro/ssh-key-action@v2
      with: 
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY}}
        known_hosts: ${{ secrets.EC2_IP }}

    - name: deploying in ec2
      env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          sudo docker stop myhomecontainer || true
          sudo docker rm myhomecontainer || true
          rm -rf ASP_HomeConnect
          git clone https://github.com/aishwarya-1226/HomeConnectPro.git
          ls -lrt
          cd HomeConnectPro
          git checkout main
          sudo docker build -t myhome:${{ github.run_number }} .
          sudo docker images
          sudo docker run --name myhomecontainer -d -p 5000:8000 myhome:${{ github.run_number }}
          sudo docker ps
        EOF
